from selenium import webdriver
driver = webdriver.Chrome()
driver.get("http://practice.automationtesting.in/")
driver.implicitly_wait(5)
driver.maximize_window()
driver.execute_script("window.scrollBy(0, 600);")
read_more_btn = driver.find_element_by_css_selector("li.post-160 a:nth-child(2)")
read_more_btn.click()
review = driver.find_element_by_css_selector(".reviews_tab > a")
review.click()
five_star = driver.find_element_by_css_selector(".star-5")
five_star.click()
review_field = driver.find_element_by_id("comment")
review_field.send_keys("good!")
name = driver.find_element_by_id("author")
name.send_keys("naaame")
email = driver.find_element_by_id("email")
email.send_keys("nikita-rumin@mail.ru")
submit = driver.find_element_by_id("submit")
submit.click()
driver.quit()
